Repository jupyterhub/oauthenticator, pull requests merged in 2021-07, with the labels that each got.

#442 [GitHub] Set JH user's email with non-public email if needed and granted scope to do so
  oauthenticator/github.py
Labels: bug

#440 [Globus] Add config username_from_email
  docs/source/getting-started.rst
  oauthenticator/globus.py
  oauthenticator/tests/test_globus.py
Labels: new

#441 [Globus] Add config to manage: allowed, admin, and blocked users through Globus groups
  docs/source/getting-started.rst
  oauthenticator/globus.py
  oauthenticator/tests/test_globus.py
Labels: new

#443 [GitLab] Fix missing use validate_server_cert config for some web requests
  oauthenticator/gitlab.py
Labels: bug

#447 Add changelog for 14.1.0
  docs/source/changelog.md
Labels: documentation
