Repository jupyterhub/oauthenticator, pull requests merged in 2021-05, with the labels that each got.

#431 ci: unpin pyjwt in test-requirements.txt
  test-requirements.txt
Labels: ci

#427 Add reference to external FeiShuAuthenticator
  README.md
Labels: documentation

#422 Note that whitelist should be used if not in 1.2
  docs/source/getting-started.rst
Labels: documentation

#434 pre-commit configured and executed
  .coveragerc
  .flake8
  .github/workflows/test.yml
  .pre-commit-config.yaml
  CONTRIBUTING.md
  README.md
  RELEASE.md
  docs/requirements.txt
  docs/source/api/index.rst.tpl
  docs/source/changelog.md
  docs/source/conf.py
  docs/source/example-oauthenticator.py
  docs/source/github.md
  docs/source/gitlab.md
  docs/source/google.md
  examples/auth_state/jupyterhub_config.py
  examples/azuread/run.sh
  examples/azuread/sample_jupyter_config.py
  examples/full/jupyterhub_config.py
  examples/generic/README.md
  oauthenticator/__init__.py
  oauthenticator/_version.py
  oauthenticator/auth0.py
  oauthenticator/azuread.py
  oauthenticator/bitbucket.py
  oauthenticator/cilogon.py
  oauthenticator/generic.py
  oauthenticator/github.py
  oauthenticator/gitlab.py
  oauthenticator/globus.py
  oauthenticator/google.py
  oauthenticator/mediawiki.py
  oauthenticator/oauth2.py
  oauthenticator/okpy.py
  oauthenticator/openshift.py
  oauthenticator/tests/conftest.py
  oauthenticator/tests/mocks.py
  oauthenticator/tests/test_auth0.py
  oauthenticator/tests/test_azuread.py
  oauthenticator/tests/test_bitbucket.py
  oauthenticator/tests/test_cilogon.py
  oauthenticator/tests/test_github.py
  oauthenticator/tests/test_gitlab.py
  oauthenticator/tests/test_globus.py
  oauthenticator/tests/test_google.py
  oauthenticator/tests/test_mediawiki.py
  oauthenticator/tests/test_oauth2.py
  oauthenticator/tests/test_okpy.py
  oauthenticator/tests/test_openshift.py
  oauthenticator/traitlets.py
  requirements.txt
  setup.py
  test-requirements.txt
Labels: maintenance

#435 docs: update to async/await in example
  examples/auth_state/jupyterhub_config.py
Labels: documentation

#437 Support custom logout url (logout_redirect_url)
  oauthenticator/auth0.py
  oauthenticator/globus.py
  oauthenticator/oauth2.py
  oauthenticator/tests/test_auth0.py
Labels: new
