Repository jupyterhub/oauthenticator, pull requests merged in 2022-06, with the labels that each got.

#513 Add changelog for 15.0.0
  docs/source/changelog.md
Labels: documentation

#477 [Bitbucket] Fix for changes to bitbucket API - /teams removed and /workspaces to be used
  oauthenticator/bitbucket.py
  oauthenticator/tests/test_bitbucket.py
Labels: maintenance

#517 [CILogon] Don't make action a required field of CILogonOAuthenticator.allowed_idps follow-up
  docs/source/migrations.md
  oauthenticator/cilogon.py
  oauthenticator/schemas/cilogon-schema.yaml
  oauthenticator/tests/test_cilogon.py
Labels: bug

#518 [CILogon] Add allowed_domains to allowed_idps config for a possiblity to restrict access based on idp + domain
  oauthenticator/cilogon.py
  oauthenticator/schemas/cilogon-schema.yaml
  oauthenticator/tests/test_cilogon.py
Labels: new
