Repository jupyterhub/oauthenticator, pull requests merged in 2023-06, with the labels that each got.

#594 [All] Authorize `allowed_users`, `admin_users`, _or_ other allowed/admin groups
  docs/source/how-to/example-oauthenticator.py
  docs/source/reference/changelog.md
  oauthenticator/auth0.py
  oauthenticator/bitbucket.py
  oauthenticator/cilogon.py
  oauthenticator/generic.py
  oauthenticator/github.py
  oauthenticator/gitlab.py
  oauthenticator/globus.py
  oauthenticator/google.py
  oauthenticator/mediawiki.py
  oauthenticator/oauth2.py
  oauthenticator/openshift.py
  oauthenticator/tests/mocks.py
  oauthenticator/tests/test_auth0.py
  oauthenticator/tests/test_azuread.py
  oauthenticator/tests/test_bitbucket.py
  oauthenticator/tests/test_cilogon.py
  oauthenticator/tests/test_generic.py
  oauthenticator/tests/test_github.py
  oauthenticator/tests/test_gitlab.py
  oauthenticator/tests/test_globus.py
  oauthenticator/tests/test_google.py
  oauthenticator/tests/test_mediawiki.py
  oauthenticator/tests/test_okpy.py
  oauthenticator/tests/test_openshift.py
Labels: enhancement, breaking

#624 maint: remove unused file common.py
  oauthenticator/common.py
Labels: maintenance

#623 maint: use tbump when making releases, update flake8/pytest/pytest-cov config
  .coveragerc
  .flake8
  .github/workflows/release.yaml
  .github/workflows/test.yml
  .readthedocs.yaml
  RELEASE.md
  oauthenticator/__init__.py
  oauthenticator/_version.py
  oauthenticator/tests/mocks.py
  oauthenticator/tests/test_cilogon.py
  pyproject.toml
  setup.py
Labels: maintenance

#625 [All] breaking, add allow_all config defaulting to False (CILogon: require allowed_idps)
  docs/source/reference/changelog.md
  oauthenticator/auth0.py
  oauthenticator/bitbucket.py
  oauthenticator/cilogon.py
  oauthenticator/generic.py
  oauthenticator/github.py
  oauthenticator/gitlab.py
  oauthenticator/globus.py
  oauthenticator/google.py
  oauthenticator/mediawiki.py
  oauthenticator/oauth2.py
  oauthenticator/openshift.py
  oauthenticator/schemas/cilogon-schema.yaml
  oauthenticator/tests/test_auth0.py
  oauthenticator/tests/test_azuread.py
  oauthenticator/tests/test_bitbucket.py
  oauthenticator/tests/test_cilogon.py
  oauthenticator/tests/test_generic.py
  oauthenticator/tests/test_github.py
  oauthenticator/tests/test_gitlab.py
  oauthenticator/tests/test_globus.py
  oauthenticator/tests/test_google.py
  oauthenticator/tests/test_mediawiki.py
  oauthenticator/tests/test_okpy.py
  oauthenticator/tests/test_openshift.py
Labels: breaking, new

#627 docs: a major refresher of the documentation
  docs/source/conf.py
  docs/source/how-to/custom-403.md
  docs/source/how-to/example-oauthenticator.py
  docs/source/how-to/writing-an-oauthenticator.md
  docs/source/index.md
  docs/source/topic/cilogon.md
  docs/source/topic/extending.md
  docs/source/topic/github.md
  docs/source/tutorials/general-setup.md
  docs/source/tutorials/provider-specific-setup/index.md
  docs/source/tutorials/provider-specific-setup/providers/auth0.md
  docs/source/tutorials/provider-specific-setup/providers/awscognito.md
  docs/source/tutorials/provider-specific-setup/providers/azuread.md
  docs/source/tutorials/provider-specific-setup/providers/bitbucket.md
  docs/source/tutorials/provider-specific-setup/providers/cilogon.md
  docs/source/tutorials/provider-specific-setup/providers/generic.md
  docs/source/tutorials/provider-specific-setup/providers/github.md
  docs/source/tutorials/provider-specific-setup/providers/gitlab.md
  docs/source/tutorials/provider-specific-setup/providers/globus.md
  docs/source/tutorials/provider-specific-setup/providers/google.md
  docs/source/tutorials/provider-specific-setup/providers/mediawiki.md
  docs/source/tutorials/provider-specific-setup/providers/okpy.md
  docs/source/tutorials/provider-specific-setup/providers/openshift.md
  examples/generic/README.md
  oauthenticator/auth0.py
  oauthenticator/azuread.py
  oauthenticator/bitbucket.py
  oauthenticator/cilogon.py
  oauthenticator/generic.py
  oauthenticator/github.py
  oauthenticator/gitlab.py
  oauthenticator/globus.py
  oauthenticator/google.py
  oauthenticator/mediawiki.py
  oauthenticator/oauth2.py
  oauthenticator/okpy.py
  oauthenticator/openshift.py
Labels: documentation
