Repository jupyterhub/oauthenticator, pull requests merged in 2023-11, with the labels that each got.

#700 ci: add test of python 3.12
  .github/workflows/test.yml
Labels: ci

#701 [CILogon] allow fnmatch based expressions in `allowed_domains`, such as `*.jupyter.org`
  oauthenticator/cilogon.py
  oauthenticator/tests/test_cilogon.py
Labels: new

#699 [CILogon] add config to specify default idp under allowed_idps
  oauthenticator/cilogon.py
  oauthenticator/tests/test_cilogon.py
Labels: new

#702 [CILogon] Add idp config `allowed_domains_claim` for use with `allowed_domains`
  oauthenticator/cilogon.py
  oauthenticator/schemas/cilogon-schema.yaml
  oauthenticator/tests/test_cilogon.py
Labels: new

#703 Add changelog for 16.2.0
  docs/source/reference/changelog.md
Labels: documentation

#704 [CILogon] Fix missing schema entry for default under allowed_idps
  oauthenticator/schemas/cilogon-schema.yaml
  oauthenticator/tests/test_cilogon.py
Labels: bug

#707 clarify what claim_groups_key is used for
  oauthenticator/generic.py
Labels: documentation
