Repository jupyterhub/oauthenticator, pull requests merged in 2023-09, with the labels that each got.

#671 Drop next_url from authorize_redirect state param
  oauthenticator/oauth2.py
  oauthenticator/tests/mocks.py
  oauthenticator/tests/test_oauth2.py
Labels: enhancement

#680 docs: fix `"generic"` renamed to `"generic-oauth"`
  docs/source/how-to/writing-an-oauthenticator.md
  docs/source/tutorials/provider-specific-setup/providers/generic.md
Labels: documentation

#684 [CILogon] Add allow_all as a idp specific config
  docs/requirements.txt
  oauthenticator/cilogon.py
  oauthenticator/schemas/cilogon-schema.yaml
  oauthenticator/tests/test_cilogon.py
Labels: new

#686 Add changelog for 16.1.0
  docs/source/reference/changelog.md
Labels: documentation
