Repository jupyterhub/oauthenticator, pull requests merged in 2023-08, with the labels that each got.

#661 [Google] Fix regression in v16 of no longer stripping username's domain if `hosted_domain` has a single entry
  oauthenticator/google.py
  oauthenticator/tests/test_google.py
Labels: bug, breaking

#662 Add changelog for 16.0.4
  docs/source/reference/changelog.md
Labels: documentation

#665 handle auth_model is None in google, globus
  oauthenticator/globus.py
  oauthenticator/google.py
  oauthenticator/oauth2.py
  oauthenticator/tests/test_generic.py
  oauthenticator/tests/test_globus.py
  oauthenticator/tests/test_google.py
Labels: bug

#666 Add changelog for 16.0.5
  docs/source/reference/changelog.md
Labels: documentation

#668 [Google, Globus, BitBucket] Ensure auth_state is JSON serializable (lists are, not sets)
  oauthenticator/bitbucket.py
  oauthenticator/generic.py
  oauthenticator/globus.py
  oauthenticator/google.py
  oauthenticator/openshift.py
  oauthenticator/tests/test_auth0.py
  oauthenticator/tests/test_azuread.py
  oauthenticator/tests/test_bitbucket.py
  oauthenticator/tests/test_cilogon.py
  oauthenticator/tests/test_generic.py
  oauthenticator/tests/test_github.py
  oauthenticator/tests/test_gitlab.py
  oauthenticator/tests/test_globus.py
  oauthenticator/tests/test_google.py
  oauthenticator/tests/test_mediawiki.py
  oauthenticator/tests/test_okpy.py
  oauthenticator/tests/test_openshift.py
Labels: bug

#670 changelog for 16.0.6
  docs/source/reference/changelog.md
Labels: documentation

#673 [Google] admin_users should like before v16 list final usernames
  oauthenticator/google.py
  oauthenticator/tests/test_google.py
Labels: bug

#675 Add changelog for 16.0.7
  docs/source/reference/changelog.md
Labels: documentation
