Repository jupyterhub/oauthenticator, pull requests merged in 2023-04, with the labels that each got.

#581 maint: declare optional dependencies for version constraints
  docs/source/tutorials/provider-specific-setup/providers/azuread.md
  setup.py
Labels: maintenance

#578 [All] Add `http_request_kwargs` config option
  oauthenticator/bitbucket.py
  oauthenticator/github.py
  oauthenticator/gitlab.py
  oauthenticator/globus.py
  oauthenticator/oauth2.py
  oauthenticator/tests/mocks.py
  oauthenticator/tests/test_oauth2.py
Labels: new

#590 maint: replace test-requirements.txt with opt. dependencies
  .github/workflows/test.yml
  CONTRIBUTING.md
  README.md
  setup.py
  test-requirements.txt
Labels: maintenance

#588 dependabot: monthly updates of github actions
  .github/dependabot.yaml
Labels: maintenance

#597 docs: fix readme badge for tests
  README.md
Labels: documentation

#604 docs: update broken links
  docs/source/how-to/migrations/upgrade-to-16.md
  docs/source/tutorials/provider-specific-setup/providers/globus.md
Labels: documentation

#603 maint: import Callable traitlet from jupyterhub
  oauthenticator/generic.py
  oauthenticator/traitlets.py
Labels: maintenance, breaking

#602 maint: cleanup already removed awscogito, azureadb2c, yandex
  oauthenticator/awscognito.py
  oauthenticator/azureadb2c.py
  oauthenticator/yandex.py
Labels: maintenance

#601 Fix bug in implementation of not yet released basic_auth config
  oauthenticator/oauth2.py
Labels: maintenance

#599 Fix Content-Type header, should be x-www-form-urlencoded for token request, and not passed for other GET requests
  oauthenticator/oauth2.py
  oauthenticator/tests/mocks.py
  oauthenticator/tests/test_auth0.py
  oauthenticator/tests/test_globus.py
Labels: bug
