Repository jupyterhub/oauthenticator, pull requests merged in 2023-01, with the labels that each got.

#568 Adjust the params of the access token request when basic auth is enabled
  oauthenticator/oauth2.py
Labels: bug

#566 ci: add dependabot for github actions and update misc versions in workflows
  .github/dependabot.yaml
  .github/workflows/publish.yml
  .github/workflows/test-docs.yaml
  .github/workflows/test.yml
  .readthedocs.yaml
Labels: ci

#561 Refactor the documentation structure
  .gitignore
  README.md
  docs/Makefile
  docs/make.bat
  docs/requirements.txt
  docs/source/_static/images/JupyterHub-OAuth-external-flow.png
  docs/source/conf.py
  docs/source/getting-started.md
  docs/source/how-to/example-oauthenticator.py
  docs/source/how-to/migrations/upgrade-to-15.md
  docs/source/how-to/writing-an-oauthenticator.md
  docs/source/index.md
  docs/source/install.md
  docs/source/reference/api/authenticator.rst.tpl
  docs/source/reference/api/index.rst.tpl
  docs/source/reference/changelog.md
  docs/source/topic/cilogon.md
  docs/source/topic/extending.md
  docs/source/topic/github.md
  docs/source/topic/gitlab.md
  docs/source/topic/google.md
  docs/source/tutorials/general-setup.md
  docs/source/tutorials/install.md
  docs/source/tutorials/provider-specific-setup/index.md
  docs/source/tutorials/provider-specific-setup/providers/awscognito.md
  docs/source/tutorials/provider-specific-setup/providers/azuread.md
  docs/source/tutorials/provider-specific-setup/providers/generic.md
  docs/source/tutorials/provider-specific-setup/providers/github.md
  docs/source/tutorials/provider-specific-setup/providers/gitlab.md
  docs/source/tutorials/provider-specific-setup/providers/globus.md
  docs/source/tutorials/provider-specific-setup/providers/google.md
  docs/source/tutorials/provider-specific-setup/providers/okpy.md
  docs/source/tutorials/provider-specific-setup/providers/openshift.md
Labels: documentation
