Repository jupyterhub/oauthenticator, pull requests merged in 2024-10, with the labels that each got.

#765 Add `enable_pkce` config, True by default
  oauthenticator/oauth2.py
  oauthenticator/tests/mocks.py
  oauthenticator/tests/test_oauth2.py
Labels: new

#763 [Google] Add `include_nested_groups` config
  oauthenticator/google.py
  oauthenticator/tests/test_google.py
Labels: new

#766 [Google] google groups config docs: properties are dictionaries
  oauthenticator/google.py
Labels: documentation

#764 [Google] Make looking up google groups far less blocking
  oauthenticator/google.py
  oauthenticator/tests/test_google.py
  setup.py
Labels: maintenance

#769 Add changelog for 17.1.0
  docs/source/reference/changelog.md
Labels: documentation

#772 Simplify retrieval of encrypted auth state
  oauthenticator/oauth2.py
Labels: maintenance
