Repository jupyterhub/oauthenticator, pull requests merged in 2024-01, with the labels that each got.

#715 temporary pin for pytest-asyncio
  setup.py
Labels: maintenance

#720 Require jupyterhub>=2.2
  .github/workflows/test.yml
  requirements.txt
Labels: breaking

#708 [Generic] Add support for `manage_groups`
  oauthenticator/generic.py
  oauthenticator/tests/test_generic.py
Labels: new
